name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "10.16.3"

      - name: Install Dependencies
        run: npm i

      - name: Build Docs
        run: npm run build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: dist